### ISSUE TITLE
SLL - Adding n Nodes - C language

### ISSUE THREAD

**Issue by Gurubalan-GIT** [Gurubalan-GIT/CCC#9]
Trying to add n number of nodes to a linked list through a loop, not by giving a choice such as :
```
while(1){
        printf("\nSLL Operations:\n");
        printf("1.Append\n");
        printf("2.Print SLL\n");
        printf("3.Exit\n");
        printf("Enter your choice:\n");
        scanf("%d",&ch);
        switch (ch)
        {
        case 1: append();
            break;
        case 2: printSLL();
            break;
        case 3: exit(0);
            break;
        default: printf("Invalid choice!");
            break;
        }
    }
```
But actually through a loop after taking response from the user the number of nodes.

**Comment by ganesh-sadanala** [comment]
I found this helpful, https://stackoverflow.com/questions/35824414/insert-n-nodes-in-a-linked-list-and-print-their-data-c

**Comment by Gurubalan-GIT** [comment]
> I found this helpful, https://stackoverflow.com/questions/35824414/insert-n-nodes-in-a-linked-list-and-print-their-data-c

Nice! Thanks, man. Works like a charm!
